# Generated by Django 3.2 on 2023-08-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0002_auto_20230816_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_number',
            new_name='phonenumber',
        ),
    ]
